### ISSUE TITLE
Compilation errors on MSVC 2015 after doctest update to 2.4.7

### ISSUE THREAD

**Issue by rmisev** [doctest/doctest#568]
## Description

Code below doesn't compile on MSVC 2015 when doctest 2.4.7 is used (but compiles fine when doctest is 2.4.6).
Compiler output:
```
d:\doctest_bug\doctest.h(821): error C2440: 'return': cannot convert from 'const char [4]' to 'const char (&&)[4]'
d:\doctest_bug\doctest.h(821): note: You cannot bind an lvalue to an rvalue reference
d:\doctest_bug\doctest.h(1320): note: see reference to function template instantiation 'T (&&doctest::detail::forward<const R>(const char (&)[4]) noexcept)' being compiled
        with
        [
            T=char [4],
            R=char [4]
        ]
d:\doctest_bug\doctest_bug.cpp(7): note: see reference to function template instantiation 'doctest::detail::Result doctest::detail::Expression_lhs<const std::string &>::operator ==<char[4],0x0>(const R (&))' being compiled
        with
        [
            R=char [4]
        ]
d:\doctest_bug\doctest_bug.cpp(7): note: see reference to function template instantiation 'doctest::detail::Result doctest::detail::Expression_lhs<const std::string &>::operator ==<char[4],0x0>(const R (&))' being compiled
        with
        [
            R=char [4]
        ]
```

### Steps to reproduce

1. Create file doctest_bug.cpp with following content:
~~~c++
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"
#include <string>

TEST_CASE("string comparison") {
    std::string str = "ABC";
    CHECK(str == "ABC");
}
~~~

2. Compile it with MSVC 2015 and Doctest 2.4.7

### Extra information

* doctest version: **2.4.7**
* Operating System: **Windows 10**
* Compiler+version: **MSVC 2015**

**Comment by onqtam** [comment]
Turns out the latest release was without MSVC 2015 testing due to the migration to a github org & relying solely on github actions - re-enabling appveyor now...

Just committed a test like your snippet and holy cow:
https://github.com/doctest/doctest/runs/4509284329?check_suite_focus=true

seems that GCC & new versions of MSVC handle it properly, but clang & MSVC 2015 error on it, and in different ways.
- MSVC cannot compile
- clang constructs the stringified version incorrectly (for `CHECK(str == "ABC2");`) which might be related to #567 :
```
-  values: CHECK( ABC == ABC2 )
+  values: CHECK( ABC == ABCABC2 )
```

**Comment by rmisev** [comment]
It seems simple fix is to remove `doctest::detail::forward` call on const lvalue reference, what I done in the commit: https://github.com/rmisev/doctest/commit/f707ccb554d60749e4843051511f7843ce75ca16
It fixes this issue, and seems doesn't break other tests.

**Comment by onqtam** [comment]
@rmisev Thanks, I'll review it in the following days!

**Comment by onqtam** [comment]
just pushed to `dev` - should be fixed, thanks!
