### ISSUE TITLE
Regression between 2.4.6 and 2.4.7

### ISSUE THREAD

**Issue by YarikTH** [doctest/doctest#571]
## Description

Following minimized code works perfectly on 2.4.6, but fails on 2.4.7

```c++
// #define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN shouldn't be defined in compilation unit to reproduce
#include <doctest/doctest.h>

#include <string>

namespace {

class B
{
public:
    const std::string& getName() const
    {
        return m_name;
    }

    std::string m_name = "B";
};

}  // namespace

TEST_CASE("Wtf?") {
    B b;

    CHECK(b.getName() == "B");
}
```
https://godbolt.org/z/Eq48fjsed (due to the godbolt limitations see "undefined reference to `main'" linker warnings as success)

Flags: "-std=c++11 -Wall -Wextra -Wpedantic -Werror"

It fails on GCC version 4.9 - 10.3 with -fpermissive warning. (GCC version 11.2 compiles it without a problem though 🤔)

```
doctest/doctest.h: In instantiation of 'void doctest::detail::fillstream(const T (&)[N]) [with T = char; long unsigned int N = 2]':
doctest/doctest.h:904:31:   required from 'static void doctest::detail::filldata<T [N]>::fill(const T (&)[N]) [with T = const char; long unsigned int N = 2]'
doctest/doctest.h:918:65:   required from 'void doctest::detail::filloss(const T (&)[N]) [with T = char; long unsigned int N = 2]'
doctest/doctest.h:933:20:   required from 'static doctest::String doctest::detail::StringMakerBase<true>::convert(const T&) [with T = char [2]]'
doctest/doctest.h:978:35:   required from 'doctest::String doctest::toString(const T&) [with T = char [2]; typename doctest::detail::enable_if<(! doctest::detail::is_enum<T>::value), bool>::type <anonymous> = true]'
doctest/doctest.h:1142:45:   required from 'doctest::String doctest::detail::stringifyBinaryExpr(const L&, const char*, const R&) [with L = std::__cxx11::basic_string<char>; R = char [2]]'
doctest/doctest.h:1320:9:   required from 'decltype (((void)((declval<L>() == declval<R>())), (doctest::detail::Result)(<brace-enclosed initializer list>()))) doctest::detail::Expression_lhs<L>::operator==(const R&) [with R = char [2]; typename doctest::detail::enable_if<(! doctest::detail::is_rvalue_reference<R>::value), void>::type* <anonymous> = 0; L = const std::__cxx11::basic_string<char>&; decltype (((void)((declval<L>() == declval<R>())), (doctest::detail::Result)(<brace-enclosed initializer list>()))) = doctest::detail::Result]'
<source>:24:5:   required from here
doctest/doctest.h:896:31: error: no match for 'operator<<' (operand types are 'std::ostream' {aka 'std::basic_ostream<char, std::char_traits<char> >'} and 'const char')
doctest/doctest.h:557:33: note: candidate: 'std::ostream& doctest::operator<<(std::ostream&, const doctest::String&)' (near match)
doctest/doctest.h:557:33: note:   conversion of argument 2 would be ill-formed:
doctest/doctest.h:896:36: error: invalid user-defined conversion from 'const char' to 'const doctest::String&' [-fpermissive]
doctest/doctest.h:519:5: note: candidate is: 'doctest::String::String(const char*)' (near match)
doctest/doctest.h:519:5: note:   conversion of argument 1 would be ill-formed:
doctest/doctest.h:896:36: error: invalid conversion from 'char' to 'const char*' [-fpermissive]
doctest/doctest.h:896:36: error: invalid conversion from 'char' to 'const char*' [-fpermissive]
doctest/doctest.h:519:24: note:   initializing argument 1 of 'doctest::String::String(const char*)'
In file included from /opt/compiler-explorer/gcc-10.3.0/include/c++/10.3.0/string:55,
                 from <source>:4:
/opt/compiler-explorer/gcc-10.3.0/include/c++/10.3.0/bits/basic_string.h:6468:5: note: candidate: 'template<class _CharT, class _Traits, class _Alloc> std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&)'
 6468 |     operator<<(basic_ostream<_CharT, _Traits>& __os,
      |     ^~~~~~~~
/opt/compiler-explorer/gcc-10.3.0/include/c++/10.3.0/bits/basic_string.h:6468:5: note:   template argument deduction/substitution failed:
doctest/doctest.h:896:31: note:   mismatched types 'const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>' and 'const char'
```

It fails on any version of clang, but with an error instead of the warning.
It fails on MSVC at least in version 19 that is accessible on Godbolt.

Using this code as a test, it's possible to bisect a broken commit.

**Comment by YarikTH** [comment]
I bisected broken commit:
```
02af672f0d3093157daecb55ce4e109ffaf2bc53 is the first bad commit
commit 02af672f0d3093157daecb55ce4e109ffaf2bc53
Author: onqtam <vik.kirilov@gmail.com>
Date:   Thu Dec 9 17:00:02 2021 +0200

    Fixes Issues #476 and #495
    
    * Fixes Issue #476 . When running executables with  stringifyBinaryExpr was accessing memory beyond bounds.This is because there is no '\0' in certain structures like  span or fixed size array. A specialization is added for array T[N]  which fills N objects of type T and then in the ostream appends an empty string without resetting the stream everytime.
    
    * Fix for #495 struct packed members which are not aligned properly and doesn't bind to universal reference. The best way to fix this is in the caller's code like annotating with CHECK (as_const(packedFoo.bar) == 0) or CHECK( static_cast <const T&> (packedFoo.bar) == 0 ). Also packedFoo.bar doesn't work with c++11/14 make_pair. The code which fails to compile with gcc works with clang without any change.
    
    This is the result of PR #491
    https://github.com/doctest/doctest/pull/491/commits/28a9dd82e8203a05f0afb7b1412c86737803e212

 doctest/doctest.h                   | 88 ++++++++++++++++++++++++++++++++-----
 doctest/parts/doctest.cpp           | 11 +++--
 doctest/parts/doctest_fwd.h         | 77 +++++++++++++++++++++++++++++---
 scripts/cmake/doctestAddTests.cmake |  4 ++
 4 files changed, 160 insertions(+), 20 deletions(-)
bisect run success
```

**Comment by YarikTH** [comment]
@navinp0304 could you look at your code and check what the problem is?

**Comment by YarikTH** [comment]
Full test:

test_regression.sh
```sh
#!/bin/bash

cd test_regression
exec ./test_regression.sh
```

test_regression/test_regression.sh
```sh
#!/bin/bash

rm -rf cmake_build
cmake -B cmake_build .
cmake --build cmake_build
```

test_regression/CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.7)

project(test_regression)

add_executable(test_regression test_main.cpp test_regression.cpp)

target_include_directories(test_regression PUBLIC ${CMAKE_CURRENT_LIST_DIR}/../)
```

test_regression/test_main.cpp
```c++
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>
```

test_regression/test_regression.cpp
```c++
#include <doctest/doctest.h>

#include <string>

namespace {

class B
{
public:
    const std::string& getName() const
    {
        return m_name;
    }

    std::string m_name = "B";
};

}  // namespace

TEST_CASE("Wtf?") {
    B b;

    CHECK(b.getName() == "B");
}
```

```
git bisect start 2.4.7 2.4.6
git bisect run ./test_regression.sh
```

**Comment by YarikTH** [comment]
More shorter example
```c++
// #define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN shouldn't be defined in compilation unit to reproduce
#include "https://raw.githubusercontent.com/doctest/doctest/2.4.7/doctest/doctest.h"

#include <string>

TEST_CASE("Wtf?") {
    //CHECK("A");

    doctest::toString("A");
}
```
https://godbolt.org/z/xnxYsPoh5

It seems that doctest::toString can't handle old good string literals anymore

```
doctest/doctest.h:896:31: error: invalid operands to binary expression ('std::ostream' (aka 'basic_ostream<char, char_traits<char>>') and 'const char')
            *getTlsOss(false) << in[i];
            ~~~~~~~~~~~~~~~~~ ^  ~~~~~
doctest/doctest.h:904:21: note: in instantiation of function template specialization 'doctest::detail::fillstream<char, 2UL>' requested here
                    fillstream(in);
                    ^
doctest/doctest.h:918:61: note: in instantiation of member function 'doctest::detail::filldata<char const[2]>::fill' requested here
        filldata<typename remove_reference <decltype(in)>::type >::fill(in);
                                                                   ^
doctest/doctest.h:933:13: note: in instantiation of function template specialization 'doctest::detail::filloss<char, 2UL>' requested here
            filloss(in);
            ^
doctest/doctest.h:978:28: note: in instantiation of function template specialization 'doctest::detail::StringMakerBase<true>::convert<char [2]>' requested here
    return StringMaker<T>::convert(value);
                           ^
<source>:9:14: note: in instantiation of function template specialization 'doctest::toString<char [2], true>' requested here
    doctest::toString("A");
             ^
doctest/doctest.h:557:33: note: candidate function not viable: no known conversion from 'const char' to 'const doctest::String' for 2nd argument
DOCTEST_INTERFACE std::ostream& operator<<(std::ostream& s, const String& in);
                                ^
/opt/compiler-explorer/gcc-11.2.0/lib/gcc/x86_64-linux-gnu/11.2.0/../../../../include/c++/11.2.0/bits/basic_string.h:6530:5: note: candidate template ignored: could not match 'basic_string<type-parameter-0-0, type-parameter-0-1, type-parameter-0-2>' against 'const char'
    operator<<(basic_ostream<_CharT, _Traits>& __os,
    ^
```

**Comment by YarikTH** [comment]
I found the root of the problem:
1. StringMakerBase is a templated class that actively uses std::ostream.
2. doctest in default configuration doesn't include `<ostream>`, but declared its own forward declared version (but not overloads (std::ostream << char for e.g.))

To solve the problem code for StringMakerBase should be rewritten without the usage of ostream in the declaration part of the header, or config DOCTEST_CONFIG_USE_STD_HEADERS become completely useless because we have to include `<ostream>` anyway.

As I understood, StringMakerBase was made for string literals and arrays in mind, so maybe forward declaring of some operators like `std::ostream& operator<<(std::ostream& os, const char);` would be enough. And yes, it seems it is enough https://godbolt.org/z/8Y76oMz5o

```c++
// #define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN shouldn't be defined in compilation unit to reproduce
//#define DOCTEST_CONFIG_USE_STD_HEADERS

#define _LIBCPP_CONCAT1(_LIBCPP_X,_LIBCPP_Y) _LIBCPP_X##_LIBCPP_Y
#define _LIBCPP_CONCAT(_LIBCPP_X,_LIBCPP_Y) _LIBCPP_CONCAT1(_LIBCPP_X,_LIBCPP_Y)

#ifndef _LIBCPP_ABI_NAMESPACE
# define _LIBCPP_ABI_NAMESPACE _LIBCPP_CONCAT(__,_LIBCPP_ABI_VERSION)
#endif

// Inline namespaces are available in Clang/GCC/MSVC regardless of C++ dialect.
#define _LIBCPP_BEGIN_NAMESPACE_STD namespace std { inline namespace _LIBCPP_ABI_NAMESPACE {
#define _LIBCPP_END_NAMESPACE_STD  } }
#define _VSTD std::_LIBCPP_ABI_NAMESPACE
_LIBCPP_BEGIN_NAMESPACE_STD _LIBCPP_END_NAMESPACE_STD

#if _LIBCPP_STD_VER >= 17
#define _LIBCPP_BEGIN_NAMESPACE_FILESYSTEM \
  _LIBCPP_BEGIN_NAMESPACE_STD inline namespace __fs { namespace filesystem {
#else
#define _LIBCPP_BEGIN_NAMESPACE_FILESYSTEM \
  _LIBCPP_BEGIN_NAMESPACE_STD namespace __fs { namespace filesystem {
#endif

#define _LIBCPP_END_NAMESPACE_FILESYSTEM \
  _LIBCPP_END_NAMESPACE_STD } }

#ifdef _LIBCPP_VERSION
#define DOCTEST_STD_NAMESPACE_BEGIN _LIBCPP_BEGIN_NAMESPACE_STD
#define DOCTEST_STD_NAMESPACE_END _LIBCPP_END_NAMESPACE_STD
#else // _LIBCPP_VERSION
#define DOCTEST_STD_NAMESPACE_BEGIN namespace std {
#define DOCTEST_STD_NAMESPACE_END }
#endif // _LIBCPP_VERSION


DOCTEST_STD_NAMESPACE_BEGIN // NOLINT (cert-dcl58-cpp)

typedef decltype(nullptr) nullptr_t;
template <class charT>
struct char_traits;
template <>
struct char_traits<char>;
template <class charT, class traits>
class basic_ostream;
typedef basic_ostream<char, char_traits<char>> ostream;

ostream& operator<<(ostream&, const char);
ostream& operator<<(ostream&, const wchar_t);

DOCTEST_STD_NAMESPACE_END

#include "https://raw.githubusercontent.com/doctest/doctest/2.4.7/doctest/doctest.h"

#include <string>

TEST_CASE("Wtf?") {
    CHECK("A");

    doctest::toString("A");
}
```

**Comment by YarikTH** [comment]
Update. I made forward declaration incorrectly. New version:
https://godbolt.org/z/sx6bM5sdh

```c++
template<class traits>
basic_ostream<char, traits>&
operator<<(basic_ostream<char, traits>&, char);

template<class traits>
basic_ostream<char, traits>&
operator<<(basic_ostream<char, traits>&, wchar_t);
```

**Comment by YarikTH** [comment]
Fixed in the dev branch somehow. Thanks @onqtam for zero feedback

**Comment by YarikTH** [comment]
I was frustrated, so I feel sorry for my previous rude words.

I didn't see how exactly it was fixed in the dev branch. I checked for my forward declaration fix and there is nothing like it in the dev branch. Also usage of `*getTlsOss(false) << in[I];` is still in the header part, so I have no idea how it is get to work.

Maybe it's better to make a reversed bisect, so at least commit in which it was fixed would be known.

**Comment by Saalvage** [comment]
Hello! I'm currently in the process of taking over the primary maintainership for doctest and I would like to extend my sincere apologies to you for the lack of feedback on this PR. Your frustratation is totally understandable, this clearly had a ton of reasearch put into it and should have been addressed.

I'm pretty sure that a PR of mine (#569) is responsible for fixing this as it rewrites some of the stringification code and was merged exactly around that time, however, how this fixed it I am also entirely unsure of.

`*getTlsOss(false) << in[I];` should not be in any header of a version that fixed this though, is it? It got replaced in the PR by a better system.

I will likely be adding a regression test for this issue in the coming days. Thank you for your efforts! 🙂

**Comment by YarikTH** [comment]
You replaced operator `*getTlsOss(false) << in[I];` with

```c++
    template<typename T>
    struct filldata
    {
        static void fill(std::ostream* stream, const T &in) {
          *stream << in;
        }
    };

    template<typename T,unsigned long N>
    struct filldata<T[N]>
    {
        static void fill(std::ostream* stream, const T (&in)[N]) {
            for (unsigned long i = 0; i < N; i++) {
                *stream << in[i];
            }
        }
    };

    // Specialized since we don't want the terminating null byte!
    template<unsigned long N>
    struct filldata<const char[N]>
    {
        static void fill(std::ostream* stream, const char(&in)[N]) {
            *stream << in;
        }
    };
```

Usage of `ostream& operator<<(ostream&, const char);` is still presented.

The problem was connected with default disabled DOCTEST_CONFIG_USE_STD_HEADERS feature. That tries instead of including stuff from `<ostream>` forward declares it. Till #491 ostream operator wasn't used in the public part of the header, so it was ok. #491 used ostream operator, but forgot to forward declare it in !DOCTEST_CONFIG_USE_STD_HEADERS section. It working just fine in case of defining DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN in the same cpp, because it includes `<ostream>` either way.

**Comment by Saalvage** [comment]
Yeah, this is bizzare.. I guess that's what we get for invoking UB by forward declaring std stuff!

**Comment by YarikTH** [comment]
Researched a bit more.

Absence of `ostream& operator<<(ostream&, const char);` is not quite correct.

The problem in #491 was caused by 
```c++
    template<typename T,unsigned long N>
    void fillstream(const T (&in)[N] ) {
        for(unsigned long i = 0; i < N; i++) {
            *getTlsOss(false) << in[i];
        }
    }
```
in the case of passing "ABC", T is char, and N is 4 and we call `operator<<(ostream&, T);` with `const char`. It is absent without forward declaration. But strangely gcc tries to call `std::ostream& operator<<(std::ostream& s, const String& in);` via converting const char to String using `String(const char* in);`. It's very weird but ok.

#569 "fixed" it in a different way. Via specialization of filldata for const.
```c++
    // Specialized since we don't want the terminating null byte!
    template<unsigned long N>
    struct filldata<const char[N]>
    {
        static void fill(std::ostream* stream, const char(&in)[N]) {
            *stream << in;
        }
    };
```
What do we do here? Actually were strange things. If we include ostream, then it declared operator<< overload for char[N] and it seems we use it. But if we don't then `in` is implicitly converted to String using `String(const char* in);` and it relies on null-terminated string in opposite to the commentary to the specialization.

It seems as a bug to me. Need to make a regression test for #476 and check both with and without DOCTEST_CONFIG_USE_STD_HEADERS in the same cpp file.

**Comment by YarikTH** [comment]
Check the difference in sintetec test:

```c++
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "https://raw.githubusercontent.com/doctest/doctest/2.4.7/doctest/doctest.h"

#include <string>

TEST_CASE("Wtf?") {
    char arr[] = {'f', 'o', 'o'};
    char arr2[] = {'b', 'a', 'r'};
    char arr3[] = {'b', 'a', 'z'};

    CHECK(arr != arr3);
}
```

## 2.4.7
https://godbolt.org/z/o7WsP454Y 
```
<source>:11: SUCCESS: CHECK( arr != arr3 ) is correct!
  values: CHECK( bazfoo != baz )
```

`values: CHECK( bazfoo != baz )` is almost correct. "bazfoo" is a bug of old stackless implementation, but only valid chars are read. Code doesn't rely on null termination.

## 2.4.8
https://godbolt.org/z/7qWEK7WGG 
```
<source>:11: SUCCESS: CHECK( arr != arr3 ) is correct!
  values: CHECK( foom���� != bazbarfoom���� )
```
As we can see the #569 added regression to changes were done in #491.

**Comment by YarikTH** [comment]
At this stage it's meta ticked about sequence of regressions in toString implementations XD

**Comment by Saalvage** [comment]
Great catch! If we were to convert the specialization to:
```cpp
// Specialized since we don't want the terminating null byte!
template<unsigned long N>
struct filldata<const char[N]>
{
    static void fill(std::ostream* stream, const char(&in)[N]) {
        *stream << String(in, in[N-1] ? N : N-1);
    }
};
```
We sould get consistent and correct behavior, right?

**Comment by YarikTH** [comment]
Look like it is. But such a ternary breaks my mind😵
```c++
// Specialized since we don't want the terminating null byte!
template<unsigned long N>
struct filldata<const char[N]>
{
    static void fill(std::ostream* stream, const char(&in)[N]) {
        unsigned long len = N-1;
        if( in[N-1] != '\0' ) // if array is not null terminated, use the whole size
            len = N;
        *stream << String(in, len);
    }
};
```
a little more verbose solution, but more clear might fit better. At least it keeps readers sanity.

**Comment by YarikTH** [comment]
Actually I'm not sure if it is a problem if string will contain additional zero byte. Because if not, then we don't need conditions. Just `String(in, N);` would be fine.

**Comment by Saalvage** [comment]
I don't think it's an issue in itself, but it would cause the String to report an incorrect length were it ever asked, therefore I think the cleaner approach is just checking it.

**Comment by YarikTH** [comment]
`char arr[] = {'b', 'a', 'z', '\0', '\0'};`
doctest::toString(arr);
which size String size is expected? 3, 4, 5? XD

**Comment by YarikTH** [comment]
If 3, then maybe 
```c++
// Specialized since we don't want the terminating null byte!
template<unsigned long N>
struct filldata<const char[N]>
{
    static void fill(std::ostream* stream, const char(&in)[N]) {
        unsigned long len = N-1;
        if( in[N-1] != '\0' )
            *stream << String(in, N); // array is not null terminated, pass N to guarantee that we don't read past the buffer
        else
            *stream << String(in); // array null terminated. Pass it to String constructor, it determinates the size via strlen call by itself
    }
};
```

**Comment by YarikTH** [comment]
Another strange example.
```c++
char arr[] = {'b', 'a', 'z', '\0', 'b', 'a', 'r'};
doctest::toString(arr);
```
Should it be 3 or 7?
If 7, then `String(in, N);` works fine. If 3, then need to see at the usage of [strnlen_s](https://en.cppreference.com/w/c/string/byte/strlen)

**Comment by Saalvage** [comment]
Hmm I'm starting to wonder whether forward declaring `operator<<` might actually be the preferable option here, as the `String` construction possibly involves a heap allocation. However then we have the problem of the unterminated character arrays again, and we won't be able to have access to `ostream::write` since you can't forward declare methods!

**Comment by YarikTH** [comment]
Actually you can make a workaround:
```c++
void writeNullTerminatedCString( std::ostream* stream, const char* str );
void writeNonNullTerminatedCString( std::ostream* stream, const char* str, size_t size );

// Specialized since we don't want the terminating null byte!
template<unsigned long N>
struct filldata<const char[N]>
{
    static void fill(std::ostream* stream, const char(&in)[N]) {
        unsigned long len = N-1;
        if( in[N-1] == '\0' )
            writeNullTerminatedCString(stream, in);
        else
            writeNonNullTerminatedCString(stream, in, N);
    }
};

// IMPL
#include <iostream>

void writeNullTerminatedCString( std::ostream* stream, const char* str )
{
    *stream << str ;
}

void writeNonNullTerminatedCString( std::ostream* stream, const char* str, size_t size )
{
     *stream.write(str, size);
}
```

**Comment by YarikTH** [comment]
Names are subject to change. Just a demo.

**Comment by YarikTH** [comment]
The more time passes I wonder why someone wanted to work with non-null terminated char arrays in the first place. So many corner cases, so much work, but is it really useful for someone?

**Comment by Saalvage** [comment]
I was about to write pretty much the same thing lol. I think for the sake of simplicity we should handle only the case where the last character is either: valid and printed or null and ignored. So we'd only have one printing function that uses `stream.write` and we pass either `N` (non-null) or `N-1` (null).

If someone needs behavior that differs from this they can simply wrap their char array in a struct with a custom `toString` implementation.

**Comment by Saalvage** [comment]
Just found a different issue! The `MESSAGE` macro uses a different stringification mechanism and it also suffers a buffer overrun when passed a char array..

**Comment by Saalvage** [comment]
We have come full-circle. We forward declare the the output operator for `const char*`!

**Comment by Saalvage** [comment]
Should finally be fixed in dev!
