### ISSUE TITLE
Implementing `DOCTEST_ASSERT_IMPLEMENT_1` as lambda prevents testing structured bindings

### ISSUE THREAD

**Issue by ChrisThrasher** [doctest/doctest#636]
## Description
Doctest 2.4.7 implements `DOCTEST_ASSERT_IMPLEMENT_1` as a do/while loop like this:
```cpp
#define DOCTEST_ASSERT_IMPLEMENT_1(assert_type, ...)                                               \
    do {                                                                                           \
        DOCTEST_ASSERT_IMPLEMENT_2(assert_type, __VA_ARGS__);                                      \
    } while(false)
```
In 2.4.8 that changed to 
```cpp
#define DOCTEST_ASSERT_IMPLEMENT_1(assert_type, ...)                                               \
    [&] {                                                                                          \
        DOCTEST_ASSERT_IMPLEMENT_2(assert_type, __VA_ARGS__);                                      \
    }()
```
The ramifications of this is that whatever is being tested must be capturable in a lambda so if something cannot be captured, it constitutes an API break between these patch versions.

This was introduced in e84f16e943fb7677a449e4e234b228d9188dd7ba.

### Steps to reproduce
Here is the example program I used to test this.
```cpp
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

#include <utility>

TEST_CASE("Structured bindings")
{
    const auto [i, d] = std::make_pair(42, 3.14);
    CHECK(i = 42);
    CHECK(d = 3.14);
}
```
AppleClang reports the following:
```
main.cpp:9:11: error: reference to local binding 'i' declared in enclosing function 'DOCTEST_ANON_FUNC_5'
    CHECK(i = 42);
          ^
main.cpp:8:17: note: 'i' declared here
    const auto [i, d] = std::make_pair(42, 3.14);
                ^
main.cpp:10:11: error: reference to local binding 'd' declared in enclosing function 'DOCTEST_ANON_FUNC_5'
    CHECK(d = 3.14);
          ^
main.cpp:8:20: note: 'd' declared here
    const auto [i, d] = std::make_pair(42, 3.14);
                   ^
```

**Comment by Saalvage** [comment]
This breaking change has been reverted in dev.

Just in case you're curious: Lambdas are used to provide a return value to the caller, which is not possible via a `do while` loop. However, instead of being enabled by default this feature is now optionally activated by defining [`DOCTEST_CONFIG_ASSERTS_RETURN_VALUES`](https://github.com/doctest/doctest/blob/dev/doc/markdown/configuration.md#doctest_config_asserts_return_values) instead.

I'm sorry for the inconvenience!

**Comment by ChrisThrasher** [comment]
I can confirm my problem is fixed when using `dev`. Thanks! Any idea when the next release will come out containing this fix?

**Comment by ChrisThrasher** [comment]
Any updates on when a new release may get cut? [SFML](https://github.com/SFML/SFML.git) is stuck with a linker bug in 2.4.7 but we can't upgrade to 2.4.8 for the reasons outlined above.

**Comment by Saalvage** [comment]
It is done!
I'm really sorry for the delay.
Thank you for sticking with doctest!

**Comment by ChrisThrasher** [comment]
Much appreciated! I'm already working on a PR to get this merged.

https://github.com/ChrisThrasher/SFML/commit/b86049fc1b32d11ccf15dc5a5d94b5ed84bf45bc
