### PR TITLE
Refactor stringification

### LINKED ISSUE #571: Regression between 2.4.6 and 2.4.7
## Description

Following minimized code works perfectly on 2.4.6, but fails on 2.4.7

```c++
// #define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN shouldn't be defined in compilation unit to reproduce
#include <doctest/doctest.h>

#include <string>

namespace {

class B
{
public:
    const std::string& getName() const
    {
        return m_name;
    }

    std::string m_name = "B";
};

}  // namespace

TEST_CASE("Wtf?") {
    B b;

    CHECK(b.getName() == "B");
}
```
https://godbolt.org/z/Eq48fjsed (due to the godbolt limitations see "undefined reference to `main'" linker warnings as success)

Flags: "-std=c++11 -Wall -Wextra -Wpedantic -Werror"

It fails on GCC version 4.9 - 10.3 with -fpermissive warning. (GCC version 11.2 compiles it without a problem though 🤔)

```
doctest/doctest.h: In instantiation of 'void doctest::detail::fillstream(const T (&)[N]) [with T = char; long unsigned int N = 2]':
doctest/doctest.h:904:31:   required from 'static void doctest::detail::filldata<T [N]>::fill(const T (&)[N]) [with T = const char; long unsigned int N = 2]'
doctest/doctest.h:918:65:   required from 'void doctest::detail::filloss(const T (&)[N]) [with T = char; long unsigned int N = 2]'
doctest/doctest.h:933:20:   required from 'static doctest::String doctest::detail::StringMakerBase<true>::convert(const T&) [with T = char [2]]'
doctest/doctest.h:978:35:   required from 'doctest::String doctest::toString(const T&) [with T = char [2]; typename doctest::detail::enable_if<(! doctest::detail::is_enum<T>::value), bool>::type <anonymous> = true]'
doctest/doctest.h:1142:45:   required from 'doctest::String doctest::detail::stringifyBinaryExpr(const L&, const char*, const R&) [with L = std::__cxx11::basic_string<char>; R = char [2]]'
doctest/doctest.h:1320:9:   required from 'decltype (((void)((declval<L>() == declval<R>())), (doctest::detail::Result)(<brace-enclosed initializer list>()))) doctest::detail::Expression_lhs<L>::operator==(const R&) [with R = char [2]; typename doctest::detail::enable_if<(! doctest::detail::is_rvalue_reference<R>::value), void>::type* <anonymous> = 0; L = const std::__cxx11::basic_string<char>&; decltype (((void)((declval<L>() == declval<R>())), (doctest::detail::Result)(<brace-enclosed initializer list>()))) = doctest::detail::Result]'
<source>:24:5:   required from here
doctest/doctest.h:896:31: error: no match for 'operator<<' (operand types are 'std::ostream' {aka 'std::basic_ostream<char, std::char_traits<char> >'} and 'const char')
doctest/doctest.h:557:33: note: candidate: 'std::ostream& doctest::operator<<(std::ostream&, const doctest::String&)' (near match)
doctest/doctest.h:557:33: note:   conversion of argument 2 would be ill-formed:
doctest/doctest.h:896:36: error: invalid user-defined conversion from 'const char' to 'const doctest::String&' [-fpermissive]
doctest/doctest.h:519:5: note: candidate is: 'doctest::String::String(const char*)' (near match)
doctest/doctest.h:519:5: note:   conversion of argument 1 would be ill-formed:
doctest/doctest.h:896:36: error: invalid conversion from 'char' to 'const char*' [-fpermissive]
doctest/doctest.h:896:36: error: invalid conversion from 'char' to 'const char*' [-fpermissive]
doctest/doctest.h:519:24: note:   initializing argument 1 of 'doctest::String::String(const char*)'
In file included from /opt/compiler-explorer/gcc-10.3.0/include/c++/10.3.0/string:55,
                 from <source>:4:
/opt/compiler-explorer/gcc-10.3.0/include/c++/10.3.0/bits/basic_string.h:6468:5: note: candidate: 'template<class _CharT, class _Traits, class _Alloc> std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&)'
 6468 |     operator<<(basic_ostream<_CharT, _Traits>& __os,
      |     ^~~~~~~~
/opt/compiler-explorer/gcc-10.3.0/include/c++/10.3.0/bits/basic_string.h:6468:5: note:   template argument deduction/substitution failed:
doctest/doctest.h:896:31: note:   mismatched types 'const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>' and 'const char'
```

It fails on any version of clang, but with an error instead of the warning.
It fails on MSVC at least in version 19 that is accessible on Godbolt.

Using this code as a test, it's possible to bisect a broken commit.

### PR DESCRIPTION
**Pull request by Saalvage**
So `StringMaker` and `StringStream` act as a pretty much completely parallel structure. This structure will be eradicated.
For the first draft I have simply removed the `StringMaker`'s body, attaching it's head to `StringStream`'s body.

The customization points are broken, as well as a few other features, namely raw memory stringification likely among others.

This (hopefully) finally fixes #571 for good!

### CODE REVIEW

**Comment by YarikTH** [comment]
Some thoughts about the situation with stringification. Imho first of all, missing unit tests should be added. Either tests for full output with -s (covering all stringification cases) or for output of toString functions for unknown types and for supported types. If doctest have it already, then the whole issue with stringification would non exist.

Also, at least such tests (if not all of them) should be added several times in different configuration matrix:
* main function in the separate cpp / main function  in the same cpp as tests
* with and without DOCTEST_CONFIG_USE_STD_HEADERS
* other similar options that can break the things

Valgrind and sanitiser configuration should be added on CI if they are not. At least they would have detected the overflow problem if they existed. Or doctest just lack of tests that fail under them.

I think that at least part of the problem is
```c++
    // cppcheck-suppress noExplicitConstructor
    String(const char* in);
```
It's a landmine waiting to explode. And it explodes in 2.4.7 and 2.4.8.

**Comment by Saalvage** [comment]
Totally agreed, it's quite ironic that a unit testing library does not utilize unit tests to test itself!

Valgrind is already being used and [sanitizers already managed to catch an issue when the appropriate tests are used](https://github.com/doctest/doctest/runs/4796631949?check_suite_focus=true)!

From the many stringification issues I don't think that that String constructor is one, I don't even think String constructors are at all considered on stringification, although I'm not sure.

File: doctest/parts/doctest_fwd.h [hunk 1]
```diff
@@ -1120,13 +1039,86 @@ class DOCTEST_INTERFACE Approx
...
+    struct StringStreamBase
+    {
+        template <typename T>
+        static void convert(std::ostream* s, const T&) {
+            writeChars(s, "{?}");
+        }
+
+        // always treat char* as a string in this context - no matter
+        // if DOCTEST_CONFIG_TREAT_CHAR_STAR_AS_STRING is defined
+        static void convert(std::ostream* s, const char* in) { *s << in; }
```
Comment (Saalvage) [inline doctest/parts/doctest_fwd.h:1058]: Is this used at this point?

**Comment by Saalvage** [comment]
TODO:
- [ ] More regression tests
- [ ] See if we can somehow get `toStream` working in MessageBuilder
- [ ] Test treating char star as string

**Comment by Saalvage** [comment]
Here's a diagram of the current stringification process, green representing customization points.
diagram

**Comment by YarikTH** [comment]
This branch has crashed in case of pointer stringification (invalid pointer actually).
https://godbolt.org/z/jW7sbj6T7

Previous releases work fine
https://godbolt.org/z/1dKozvq7T

**Comment by YarikTH** [comment]
Also, my stringification test points me to some improvements:
```
Fundamental types:
    float:                          1.1f
    double:                         2.2
    long double:                    3.3
С arrays:
    const char[]:                   foo
    char[]:                         bar
    const int[]:                    123
    int[]:                          456
```
=>
```
Fundamental types:
    float:                          1.1f
    double:                         2.2
    long double:                    3.3L
С arrays:
    const char[]:                   foo
    char[]:                         bar
    const int[]:                    [1, 2, 3]
    int[]:                          [4, 5, 6]
```
Great work, I almost reported strange stringification of non-char arrays 👍

**Comment by YarikTH** [comment]
toString ignored overloaded ostream operator for enum class values.
https://godbolt.org/z/sYPEb3Y1h

**Comment by YarikTH** [comment]
Call docstring::toString with pointer types spoils internal tloss. Reproducible in 2.4.8 and in dev, fixed in this PR. Great work!
https://godbolt.org/z/fc4cfMj3K

**Comment by YarikTH** [comment]
I think that define to disable tloss optimization is very desirable. It's unstable feature that causes too much problems. Imho it should be disabled by default and switched on manually if someone really wants it to speed up tests runtime.

**Comment by YarikTH** [comment]
Yet another find. The toString output of wchar_t, char16_t and char32_t depend on the cxx standard. It outputs integer representation until c++17, but in c++20 it becomes unknown for doctest.
https://godbolt.org/z/7axaaoTKx

Tested both on GCC and clang.

**Comment by Saalvage** [comment]
> This branch has crashed in case of pointer stringification (invalid pointer actually). https://godbolt.org/z/jW7sbj6T7
> 
> Previous releases work fine https://godbolt.org/z/1dKozvq7T
> 
> It crashed in
> 
> ```c++
>     template <typename T>
>     String rawMemoryToString(const T& object) {
>         return rawMemoryToString(&object, sizeof(object));
>     }
> ```
> 
> It seems that the presumption that not null pointer points to valid data is principally incorrect.
> 
> My example is kind of syntetic, but for example there is such thing as an end iterator for std::array or C array. It points past the array data so, dereferencing of it, it is an error.
> 
> ```c++
> int a[] = { 1, 2, 3 };
> auto it = std::find( std::begin(a), std::end(a), 2 );
> CHECK( it != std::end(a) ); // both it and end can point at the invalid memory past the buffer
> ```

This is really weird because I didn't really change anything about the stringification of pointers.. Good catch!

**Comment by YarikTH** [comment]
I've made stringify test or more or less sandbox where it can be easily checked
https://github.com/YarikTH/doctest_stringify_test

It uses doctest itself and ApprovalTests.cpp to continuously compare differences in outputs. Test contains all fundamental types, custom classes and most of container and utility std classes. It optionally uses stl_stringifier.h to check how it does its work.

All of the finds were done in the process of developing it.

**Comment by YarikTH** [comment]
About pointer stringification. There is already ostream operator for pointer types. But doctest uses its own approach to their stringification. And this approach is not consistent with stringification of shared_prt and unique_ptr because doctest doesn't handle them)
https://godbolt.org/z/dfxsW5jG4

File: doctest/doctest.h [hunk 2]
```diff
@@ -445,7 +455,6 @@ DOCTEST_GCC_SUPPRESS_WARNING_POP
 #ifndef DOCTEST_CONFIG_INCLUDE_TYPE_TRAITS
 #define DOCTEST_CONFIG_INCLUDE_TYPE_TRAITS
 #endif // DOCTEST_CONFIG_INCLUDE_TYPE_TRAITS
-#include <cmath>
 #include <cstddef>
 #include <ostream>
 #include <istream>
```
Comment (YarikTH) [inline doctest/doctest.h:460]: `#include<iosfwd>` might be sufficient here. Because it declares but not defines both ostream and istream and its inclusion times are non-existing comparing to ostream and istream see https://artificial-mind.net/projects/compile-health/
But I'm not sure if DOCTEST_CONFIG_USE_STD_HEADERS is properly tested.

**Comment by Saalvage** [comment]
Honestly the rat's tail of this is unimaginable, I am almost certain there is more weird and broken stuff waiting in the nooks and crannies here, but at some point we'll just have to bite the bullet and go through with it. Can't have people waiting on 2.4.9 forever!
