### ISSUE TITLE
Packed fields can't be accessed in 2.4.6

### ISSUE THREAD

**Issue by rhssk** [doctest/doctest#495]
## Description
Starting with 2.4.6, members of packed structs can't be accessed in `CHECK` macros. Doing so generates a compile error: `cannot bind packed field 'X' to 'Y'`. Versions 2.4.5 and earlier do not have this issue.

### Steps to reproduce
```cpp
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"

struct Foo {
	unsigned bar;
	unsigned char baz;
};

struct PackedFoo {
	unsigned bar;
	unsigned char baz;
} __attribute__((packed));

TEST_CASE("") {
	Foo foo{};
	PackedFoo packedFoo{};

	CHECK(foo.bar == 0); // OK
	CHECK(packedFoo.bar == 0); // Compile error
}
```
```bash
> g++ main.cpp -o main
In file included from main.cpp:2:
main.cpp: In function ‘void _DOCTEST_ANON_FUNC_8()’:
main.cpp:19:18: error: cannot bind packed field ‘packedFoo.PackedFoo::bar’ to ‘unsigned int&’
   19 |  CHECK(packedFoo.bar == 0);
      |        ~~~~~~~~~~^~~
doctest.h:1837:9: note: in definition of macro ‘DOCTEST_WRAP_IN_TRY’
 1837 |         x;                                                                                         \
      |         ^
doctest.h:2086:9: note: in expansion of macro ‘DOCTEST_ASSERT_IMPLEMENT_2’
 2086 |         DOCTEST_ASSERT_IMPLEMENT_2(assert_type, __VA_ARGS__);                                      \
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
doctest.h:2104:28: note: in expansion of macro ‘DOCTEST_ASSERT_IMPLEMENT_1’
 2104 | #define DOCTEST_CHECK(...) DOCTEST_ASSERT_IMPLEMENT_1(DT_CHECK, __VA_ARGS__)
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
doctest.h:2573:20: note: in expansion of macro ‘DOCTEST_CHECK’
 2573 | #define CHECK(...) DOCTEST_CHECK(__VA_ARGS__)
      |                    ^~~~~~~~~~~~~
main.cpp:19:2: note: in expansion of macro ‘CHECK’
   19 |  CHECK(packedFoo.bar == 0);
      |  ^~~~~
```

### Extra information
* doctest version: **2.4.6**
* Operating System: **Arch Linux**
* Compiler+version: **gcc (GCC) 10.2.0**

**Comment by rhssk** [comment]
After bisecting it appears that the issue is introduced in 318e1dff9720b5c7abffc05b1bcbf231c2f1ad38

**Comment by onqtam** [comment]
this should be fixed in the current dev branch!

**Comment by Saalvage** [comment]
I have no idea what black magic was used to fix this originally, however, https://github.com/doctest/doctest/commit/ce13bc44b99c87e918b98bdadb17008d2dd54d55 broke it again and arguably for a more useful fix.

#652 will likely break it further still.

I'm honestly not exactly sure on how to address this, I'm just gonna be bold and put the blame on GCC here for not having proper support for binding their vendor-specific packed struct's members to universal references (they bind to non-const l-values, which is correct, but forbidden for packed struct members!)

Maybe some day someone will come up with a fix.

**Comment by cdeln** [comment]
I don't think this is a GCC bug, it's most likely ok according if you dig deep enough into the standard ;)

I'll describe what happens below, and follow up with some workarounds.
The problem lies in expression decomposer which provides two overloads of `operator <<`, one with a universal reference, and one with a const reference. Uni refs are always resolved before const refs. 
I'm not sure under what circumstances the const reference specialization will even resolved to even, does anyone know? The universal ref has to decay into either a normal ref or a const ref. Since the struct instance is not declared const, it selects the non-const path and decays the uni ref into a normal ref, which is disallowed for packed fields.

Now, workarounds for packed fields are either of these
1) Declare the struct instance as const
2) Add one layer of indirection by a copy

This code compiles and runs fine

```cpp
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

struct PackedFoo {
	int bar;
} __attribute__((packed));

template <typename T>
T unpack(T x) {
    return x;
}

TEST_CASE("packed-struct") {
    PackedFoo mfoo {};
    const PackedFoo cfoo{};
    REQUIRE(unpack(mfoo.bar) == 0);
    REQUIRE(cfoo.bar == 0);
}
```
