### ISSUE TITLE
TEST_CASE_CLASS is broken in v2.4.8

### ISSUE THREAD

**Issue by BerengerBerthoul** [doctest/doctest#608]
## Description
`TEST_CASE_CLASS ` works with version 2.4.7, not with v2.4.8. It is broken by commit 95a78536.

### Steps to reproduce

`TEST_CASE_CLASS ` is not documented nor tested by the CI.  However if I take [this example ](https://github.com/doctest/doctest/issues/76#issuecomment-462040669) proposed in the description of the feature, and simplify it :

```
#include "doctest/doctest.h"

class my_type {
    int data = 5;

    TEST_CASE_CLASS("all_to_all_v 2") {
        my_type local;
        CHECK(local.data == 2);
    }
};
```
This does not compile. GCC error message:
 ```
doctest.h:1980:64: error: 'DOCTEST_ANON_VAR_4' was not declared in this scope; did you mean 'DOCTEST_ANON_VAR_0'?
 1980 |     global_prefix DOCTEST_GLOBAL_NO_WARNINGS(DOCTEST_ANONYMOUS(DOCTEST_ANON_VAR_), 
```

### Extra information

Note that a (better?) alternative to `TEST_CASE_CLASS` is mentioned [here](https://github.com/doctest/doctest/issues/76#issuecomment-808603422). Maybe we should try to implement the more flexible feature rather than fixing this one.

On a personal note, I was just trying to check if `TEST_CASE_CLASS` could solve my problem (a bug in `MPI_TEST_CASE` with several `SUBCASE`). But it will not (even when fixed). So I personally don't need the fix.

* doctest version: v2.4.8
* Operating System: Linux
* Compiler+version: GCC 11

**Comment by avoirtech** [comment]
There is also an issue with the TEST_CASE_CLASS with templates, see here: https://github.com/doctest/doctest/issues/718

**Comment by cdeln** [comment]
As discussed in #76 , this feature is questionable to begin with. I can confirm that it is broken, so we should probably remove it completely (luckily it's barely documented so not too many people should depend on it).
It's unfortunate to remove a feature once it's in the API, but I think it's the only way. It could be done by giving the user a clear error message about it's removal if one tries to use the `TEST_CASE_CLASS` macro, and pointers to workaround.

**Comment by mitchgrout** [comment]
Sorry this issue hasn't been addressed earlier. Unfortunately I'm unable to reprod on either gcc-15.1 or clang-19 w/ the dev-branch. I'm going to close for the time being, but if there's renewed interest I'm happy to re-assess.
