### ISSUE TITLE
Error triggered by comparing typeid with new doctest 2.4.8

### ISSUE THREAD

**Issue by JazzSuite** [doctest/doctest#632]
## Description
I wanted to check the typeid off two objects wich should be same. The test should be fine but it doesnt even compile (the error is shown below in the small example). It is a problem of the visual studio compiler, because it does not have any compile errors with clang and gcc. 
It only works if I define a local variable, wich I check then. 

It looks like someone had the same (?) problem (https://developercommunity.visualstudio.com/t/c2326-capture-error-in-catch-block-of-nested-lambd/1125519) and microsoft said that it would be fixed, but it doesnt seems like. 

FYI: The problem startet a few days ago when i updated doctest from 2.4.0 to 2.4.8. With 2.4.0 everything worked out fine. 

I will report this error to microsoft but dont know if they will fix it, and if so when they will do it.

Thank you ;)

### Steps to reproduce
```cpp
#include "doctest/doctest.h"

TEST_CASE("doctest_test"){
    struct Base {
        virtual void foo() {}; //virtual function needed to cause bug
        virtual ~Base() = default;
    };

    Base b;
    Base& rb{b};
    Base *pb = &b;

//    C:\...\test_doctest.cpp(13,5): error C2326: "auto DOCTEST_ANON_FUNC_5::<lambda_4eadbc347a23bfe0fb4260b9ce06dcf0>::operator ()(void) const": function cannot access "rb" [C:\...\_tests\test_doctest.vcxproj]
//    C:\...\test_doctest.cpp(13,5): error C2326: "auto DOCTEST_ANON_FUNC_5::<lambda_4eadbc347a23bfe0fb4260b9ce06dcf0>::operator ()(void) const": function cannot access "pb" [C:\...\_tests\test_doctest.vcxproj]
      CHECK(typeid(rb) == typeid(*pb)); //fails with the error messages above

    const bool test2 = typeid(rb) == typeid(*pb);
    CHECK(test2); //succeeds
}
```
### Extra information

* doctest version: **v2.4.8**
* Microsoft Windows 10**
*  Visual Studio Compiler Version 19.31.31104 for x64**
* Dont know if this is relevant but I use cmake.

**Comment by Saalvage** [comment]
This seems to have been fixed on the dev branch, could you confirm?

**Comment by JazzSuite** [comment]
It seems like it fixed these errors. But with the dev doctest (commit 8de4cf7e759c55a89761c25900d80e01ae7ac3fd, because i couldnt checkout the newer ones) there are a bunch of new problems. But now with all compilers. I will talk to that with a software developer since im just a working student and probably will make an issue for the new problems if there is no problem with our codebase.

**Comment by Saalvage** [comment]
Alright, so I'll be closing this then. The `dev` branch should be non-breaking, so I'd happily learn about any issues you're having.
Thank you for your contribution!
