### ISSUE TITLE
Clang in MSVC mode broken in 2.4.9

### ISSUE THREAD

**Issue by u3shit** [doctest/doctest#673]
## Description
After updating doctest to 2.4.9, it broke clang in msvc mode again. e8ba771d4b4cf90cb99e011ef01059dd6533d39c introduced some changes, using `::operator<<` in stringification, possibly to workaround msvc bugs, but it causes bugs in clang instead:
```
doctest.h:978:56: error: no member named 'operator<<' in the global namespace
    struct has_global_insertion_operator<T, decltype(::operator<<(declval<std::ostream&>(), declval<const T&>()), void())> : types::true_type { };
                                                     ~~^
1 error generated.
```

https://github.com/doctest/doctest/blob/b7c21ec5ceeadb4951b00396fc1e4642dd347e5f/doctest/doctest.h#L973
https://github.com/doctest/doctest/blob/b7c21ec5ceeadb4951b00396fc1e4642dd347e5f/doctest/doctest.h#L1124
Replacing these `#if`s with `#if !DOCTEST_CLANG && (defined(_MSC_VER) && _MSC_VER <= 1900)` seem to fix the problem for me.

### Steps to reproduce
Just include the doctest header.

### Extra information
* doctest version: **v2.4.9**
* Operating System: **Gentoo linux**
* Compiler+version: **clang 8.0.1 with msvc12 stdlibs**

**Comment by Saalvage** [comment]
What an interesting configuration. Is it equivalent to just running an old Visual Studio version with clang? If not, how did you configure it? I'd like to include a CI run for this so it won't break in the future. Any help towards that goal would be greatly appreciated @u3shit, but if you don't have the time/motivation I'd totally understand that too! Either way, this should be fixed in 2.4.10, which is hopefully releasing this week.

**Comment by u3shit** [comment]
It's more like asking clang to output code that is ABI compatible with MSVC than running an old version of MSVC. I use it because I have to produce a DLL that will be injected into a process compiled using a specific MSVC version and it needs to share stl containers between them, which is not supported between different MSVC versions, but I didn't want to restrict myself to the pre-c++11 support given by said MSVC version, so I'm stuck with this abomination. Definitely not a common use case. Back in the time I put together some "documentation" here, but if you're using a windows host it should be as simple as installing MSVC and clang on the same machine, and running clang-cl instead of cl.
https://git.neptards.moe/neptards/libshit/src/branch/master/COMPILE.md#cross-compiling-to-windows
(This also project also have some "patches" to the includes, to have some rudimentary c++17 support, so I'm not sure whether you should base anything on this. I have an other configuration, where I use libc++ on Windows on clang in MSVC mode (this will mean the c runtime and low-level functions (memory allocation, exception handling, etc) will be handled by the msvc runtime, while the rest of c++ standard lib is by libc++), I think that also broke some assumptions made by some libraries I use)

**Comment by Saalvage** [comment]
Fixed in dev!
