### ISSUE TITLE
New doctest version gives me an error: reference to local binding '...' declared in enclosing function 'DOCTEST_ANON_FUNC_16'

### ISSUE THREAD

**Issue by a4z** [doctest/doctest#638]
## Description

I updated some older code that used doctest 2.3.5 to doctest 2.4.8

with 2.4.8 I get now errors 

```
error: reference to local binding '...' declared in enclosing function 'DOCTEST_ANON_FUNC_16'
```

### Steps to reproduce

Code producing the problem looks like that

```
SCENARIO("fetch url data")
{
    GIVEN("a valid URL")
    {
        std::string good_url = "http://example.com/api/latest";
        WHEN("making a request")
        {
            const auto [res, data] = fetch_url(good_url);
            THEN("a valid flagged result is returned")
            {
                CHECK_EQ(res, CURLE_OK);
            }
        }
    }
}

```

This works perfectly find with doctest 2.3.5 , but does not compile with 2.4.8

The error looks something like
```
where/ever_tests.cpp:82:26: error: reference to local binding 'res' declared in enclosing function 'DOCTEST_ANON_FUNC_16'
                CHECK_EQ(res, CURLE_OK);
                         ^
where/ever_tests.cpp:79:25: note: 'res' declared here
            const auto [res, data] = fetch_url(good_url);
```

Edit: for info, fetch_url returns a `std::tuple<CURLcode, std::string>` 

### Extra information

* doctest version: **v2.4.8**
* Operating System: **MacOS Monterey**
* Compiler+version: **Apple clang version 13.1.6 **

**Comment by Saalvage** [comment]
Could you test if the head of the dev branch fixes this?

I'm fairly certain this is a duplicate of #636. See my explanation there on why this exists in the first place if you're curious.

If it is indeed the same issue, then I'm really sorry for the inconvenience and I'll try my best to release a fix in the form of v2.4.9 within the month!

**Comment by a4z** [comment]
This looks very much like the root cause, 
I can and will test it tomorrow , will report back

**Comment by a4z** [comment]
I can confirm, the code fails with master branch but works with the current dev branch.

I close this issue and wait with the update of my code until the next release. 
Thanks for the fast feedback!
